### ISSUE TITLE
Cydia

### ISSUE THREAD

**Issue by phil71994** [FlexMonkey/Plum-O-Meter#1]
My issue is that i'd like to have this but i am too dumb to compile it myself. Could you please make it available on cydia?

**Comment by FlexMonkey** [comment]
Hi, I suspect Apple won't look kindly on me deploying code to Cydia and it may well invalidate my developer contract with them, so this isn't something I want to do I'm afraid.

**Comment by phil71994** [comment]
Apple doesn't care at all. There are many cydia developers that also have apps in the appstore, for example the creator of ProTube. I think Ryan Petrich does also have some Apps in the AppStore. Most Cydia developers have a developer account at apple, so dont worry about that

**Comment by phil71994** [comment]
If you really dont want to put it on cydia, could you just send me the app in an email please?

**Comment by FlexMonkey** [comment]
No worries, I'll sort this out later today

**Comment by phil71994** [comment]
Sort out what? Please keep us up to date, there are many people that like your project and want to download your app.

**Comment by casper6863** [comment]
> Sort out what? Please keep us up to date, there are many people that like your project and want to download your app.
